### ISSUE TITLE
Schema.add is not a function

### ISSUE THREAD

**Issue by throrin19** [naxmefy/mongoose-naxmefy-autoinc-field#1]
Hi, I test your plugin and I have this error : 

```
[TypeError: schema.add is not a function]
```

After research in your code, the error is your `naxmefyAutoIncPlugin` declaration. The first parameter is the scema and the second is the autoinc options **BUT** In your example, you used only one param in the function : Your autoInc options.

If I console.log the `schema` value in your code, I get the autoInc configuration options, Not My Schema.

**Comment by naxmefy** [comment]
Hi - i recommend to use mongoose-sequence
